config/routes.rb
Rails.application.routes.draw do
  resources :airports, only: [:index, :show]
  root to: 'airports#index'

  # resources :regions
  # resources :countries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/airport.rb
require 'normalize_country'

class Airport < ApplicationRecord


  def self.from_source_hash(h)
    Airport.new(
        oa_id:           h['id'],
        ident:           h['ident'],
        airport_type:    h['type'],
        name:            h['name'],
        lat:             h['latitude_deg'].to_f,
        long:            h['longitude_deg'].to_f,
        elevation_ft:    h['elevation_ft'],
        continent:       h['continent'],
        iso_country:     h['iso_country'],
        iso_region:      h['iso_region'],
        municipality:    h['municipality'],
        scheduled_service: h['scheduled_service'] == 'yes',
        gps_code:        h['gps_code'],
        iata_code:       h['iata_code'],
        local_code:      h['local_code'],
        home_link:       h['home_link'],
        wikipedia_link:  h['wikipedia_link'],
        keywords:        h['keywords']
    )
  end


  def to_h
    {
        id:                id,
        oa_id:             oa_id,
        ident:             ident,
        airport_type:      airport_type,
        name:              name,
        lat:               lat,
        long:              long,
        elevation_ft:      elevation_ft,
        continent:         continent,
        iso_country:       iso_country,
        iso_region:        iso_region,
        municipality:      municipality,
        scheduled_service: scheduled_service,
        gps_code:          gps_code,
        iata_code:         iata_code,
        local_code:        local_code,
        home_link:         home_link,
        wikipedia_link:    wikipedia_link,
        keywords:          keywords
    }
  end


  def country_name
    NormalizeCountry.convert(iso_country)
  end


  def lat_long_valid?
    lat != 0.0 || long != 0.0
  end


  def has_home_link?
    home_link && home_link.size > 0
  end


  # URL for this location on Google Maps. The map is of the lat/long coordinates only so
  # the airport might not be labelled. In addition, because we are not searching for the
  # place name, we need to zoom in quite a bit to guarantee that the airport is visible.
  # Reference: https://developers.google.com/maps/documentation/urls/guide
  def map_link
    "https://www.google.com/maps/@?api=1&map_action=map&zoom=14&center=#{lat},#{long}"
  end


  def flight_radar_24_link
    if iata_code
      "https://www.flightradar24.com/airport/#{iata_code.downcase}"
    elsif lat_long_valid?
      "https://www.flightradar24.com/#{lat},#{long}/8"
    else
      nil
    end
  end
end


=begin
- id: '323361'
  ident: 00AA
  type: small_airport
  name: Aero B Ranch Airport
  latitude_deg: '38.704022'
  longitude_deg: "-101.473911"
  elevation_ft: '3435'
  continent: NA
  iso_country: US
  iso_region: US-KS
  municipality: Leoti
  scheduled_service: 'no'
  gps_code: 00AA
  iata_code:
  local_code: 00AA
  home_link:
  wikipedia_link:
  keywords:
=end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  before_action :set_airport, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /airports
  # GET /airports.json
  def index
    @airports = Airport.order("#{sort_column} #{sort_direction}").page params[:page]
  end

  # GET /airports/1
  # GET /airports/1.json
  def show
  end

  # GET /airports/new
  def new
    @airport = Airport.new
  end

  # GET /airports/1/edit
  def edit
  end

  # POST /airports
  # POST /airports.json
  def create
    @airport = Airport.new(airport_params)

    respond_to do |format|
      if @airport.save
        format.html { redirect_to @airport, notice: 'Airport was successfully created.' }
        format.json { render :show, status: :created, location: @airport }
      else
        format.html { render :new }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airports/1
  # PATCH/PUT /airports/1.json
  def update
    respond_to do |format|
      if @airport.update(airport_params)
        format.html { redirect_to @airport, notice: 'Airport was successfully updated.' }
        format.json { render :show, status: :ok, location: @airport }
      else
        format.html { render :edit }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airports/1
  # DELETE /airports/1.json
  def destroy
    @airport.destroy
    respond_to do |format|
      format.html { redirect_to airports_url, notice: 'Airport was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airport
      @airport = Airport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airport_params
      params.require(:airport).permit(%i(
          oa_id,
          ident
          airport_type
          name
          lat
          long
          elevation_ft
          continent
          iso_country
          iso_region
          municipality
          scheduled_service
          gps_code
          iata_code
          home_link
          wikipedia_link
          keywords
      ))
    end

  # For sortable tables, from https://richonrails.com/articles/sortable-table-columns
  private
  def sortable_columns
    %w(iata_code  name  iso_country  lat  long  elevation_ft  home_link  wikipedia_link)
  end

  def sort_column
    sortable_columns.include?(params[:column]) ? params[:column] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/airports_helper.rb
module AirportsHelper

  UP_ARROW_CHAR   = "\u2b06"  #  "⬆"
  DOWN_ARROW_CHAR = "\u2b07"  #  "⬇"

  def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    arrow = sort_direction == "asc" ? UP_ARROW_CHAR : DOWN_ARROW_CHAR
    arrow = column == sort_column ? arrow : ""
    link_to "#{title} #{arrow}".html_safe, {column: column, direction: direction}
  end

end

app/views/airports/_form.html.erb
<%= form_with(model: airport, local: true) do |form| %>
  <% if airport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(airport.errors.count, "error") %> prohibited this airport from being saved:</h2>

      <ul>
      <% airport.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :oa_id %>
    <%= form.text_field :oa_id %>
  </div>

  <div class="field">
    <%= form.label :ident %>
    <%= form.text_field :ident %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat %>
  </div>

  <div class="field">
    <%= form.label :long %>
    <%= form.text_field :long %>
  </div>

  <div class="field">
    <%= form.label :elevation_ft %>
    <%= form.text_field :elevation_ft %>
  </div>

  <div class="field">
    <%= form.label :continent %>
    <%= form.text_field :continent %>
  </div>

  <div class="field">
    <%= form.label :iso_country %>
    <%= form.text_field :iso_country %>
  </div>

  <div class="field">
    <%= form.label :iso_region %>
    <%= form.text_field :iso_region %>
  </div>

  <div class="field">
    <%= form.label :municipality %>
    <%= form.text_field :municipality %>
  </div>

  <div class="field">
    <%= form.label :scheduled_service %>
    <%= form.text_field :scheduled_service %>
  </div>

  <div class="field">
    <%= form.label :gps_code %>
    <%= form.text_field :gps_code %>
  </div>

  <div class="field">
    <%= form.label :iata_code %>
    <%= form.text_field :iata_code %>
  </div>

  <div class="field">
    <%= form.label :home_link %>
    <%= form.text_field :home_link %>
  </div>

  <div class="field">
    <%= form.label :wikipedia_link %>
    <%= form.text_field :wikipedia_link %>
  </div>

  <div class="field">
    <%= form.label :keywords %>
    <%= form.text_field :keywords %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/airports/edit.html.erb
<h1>Editing Airport</h1>

<%= render 'form', airport: @airport %>

<%= link_to 'Show', @airport %> |
<%= link_to 'Back', airports_path %>

app/views/airports/index.html.erb
<p style="margin-bottom: 0" id="notice"><%= notice %></p>

<div class="container-fluid">
  <h1 class="page-title">Airport Information from <a href="http://OurAirports.com/data">OurAirports.com</a></h1>
  <br />

<table class="table table-bordered">
  <thead align="center">
    <tr>
      <th style="width:8em;"><%= sort_link "iata_code" %></th>
      <th style="width:22em;"><%= sort_link "name" %></th>
      <th style="width:10em;"><%= sort_link 'lat', 'Latitude' %></th>
      <th style="width:10em;"><%= sort_link 'long', 'Longitude' %></th>
      <th><%= sort_link 'elevation_ft', 'Elev. (ft)' %></th>
      <th><%= sort_link 'iso_country', 'Country' %></th>
      <th>Map</th>
      <th><%= sort_link 'home_link', 'Home Page' %></th>
      <th><%= sort_link 'wikipedia_link', 'Wikipedia' %></th>
      <th><%= sort_link 'flight_radar_24_link', 'FR 24' %></th>
    </tr>
  </thead>

  <tbody>
    <% @airports.each do |airport| %>
      <tr>
        <% if airport.iata_code %>
          <td align="center"><%= link_to airport.iata_code, airport %></td>
        <% else %>
          <td />
        <% end %>

        <td><%= link_to airport.name, airport %></td>

        <td align="right"><%= airport.lat&.round(6) %></td>
        <td align="right"><%= airport.long&.round(6) %></td>
        <td align="right"><%= airport.elevation_ft %></td>
        <td align="center" title="<%= airport.country_name %>"><%= airport.iso_country %></td>

        <% if airport.lat_long_valid? %>
          <td align="center"><%= link_to 'Map', airport.map_link, target: '_blank' %></td>
        <% else %>
          <td />
        <% end %>

        <% if airport.has_home_link? %>
          <td align="center"><%= link_to 'Home', airport.home_link, target: '_blank' %></td>
        <% else %>
          <td />
        <% end %>

        <% if airport.wikipedia_link %>
          <td align="center"><%= link_to 'Wikipedia', airport.wikipedia_link, target: '_blank' %></td>
        <% else %>
          <td />
        <% end %>

        <% if airport.flight_radar_24_link %>
          <td align="center"><%= link_to 'FR', airport.flight_radar_24_link, target: '_blank' %></td>
        <% else %>
          <td />
        <% end %>

        <!--        <td><%#= link_to 'Edit', edit_airport_path(airport) %></td>-->
        <!--        <td><%#= link_to 'Destroy', airport, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @airports, theme: 'twitter-bootstrap-4' %>

<%#= link_to 'New Airport', new_airport_path %>
</div>

app/views/airports/new.html.erb
<h1>New Airport</h1>

<%= render 'form', airport: @airport %>

<%= link_to 'Back', airports_path %>

app/views/airports/show.html.erb
<%
  def link_text(url)
    if url && url.length > 0
      link_to url, url, target: '_blank'
    else
      nil
    end
  end


  def form_element(_id, label_text, current_content, is_link = false)
    %Q{
    <dt class="col-sm-3">#{label_text}</dt>
    <dd class="col-sm-9">#{current_content || '-'}</dd>
    }.html_safe
  end


  def country_string
    em_dash = "\u2014"
    "#{@airport.iso_country} #{em_dash} #{@airport.country_name}" # \u2014 = em dash
  end

  def title_text
    @airport.iata_code ? "#{@airport.iata_code}: #{@airport.name}" : @airport.name
  end
%>


<div class="container">

  <br />
  <br />
  <h1><%= title_text %> <small class="text-muted"><%= "  (#{@airport.country_name})" %></small></h1>
  <br />
  <br />

  <dl class="row">
    <%= form_element('iata_code',          'IATA Code',          @airport.iata_code) %>
    <%= form_element('name',               'Name',               @airport.name) %>
    <%= form_element('ident',              'Identification',     @airport.ident) %>
    <%= form_element('airport_type',       'Airport Type',       @airport.airport_type) %>
    <%= form_element('lat',                'Latitude',           @airport.lat) %>
    <%= form_element('long',               'Longitude',          @airport.long) %>
    <%= form_element('elevation_ft',       'Elevation (ft)',     @airport.elevation_ft) %>
    <%= form_element('continent',          'Continent',          @airport.continent) %>
    <%= form_element('iso_country',        'Country',            country_string) %>
    <%= form_element('iso_region',         'ISO Region Code',    @airport.iso_region) %>
    <%= form_element('municipality',       'Municipality',       @airport.municipality) %>
    <%= form_element('scheduled_service',  'Scheduled Service?', @airport.scheduled_service) %>
    <%= form_element('gps_code',           'GPS Code',           @airport.gps_code) %>
    <%= form_element('map_link',           'Map Link',           link_text(@airport.map_link)) %>
    <%= form_element('home_link',          'Home Link',          link_text(@airport.home_link)) %>
    <%= form_element('wikipedia_link',     'Wikipedia Link',     link_text(@airport.wikipedia_link)) %>
    <%= form_element('flight_radar_24_link', 'Flight Radar 24 Link', link_text(@airport.flight_radar_24_link)) %>
    <%= form_element('keywords',           'Keywords',           @airport.keywords) %>
  </dl>

    <%= link_to 'Back', :back, class: 'btn  btn-primary' %>
</div>
</div>